---
title: "BFW Equilibrium Gender LFP and Wage Code Companion"
author: "Sonia R. Bhalotra, Manuel Fernández, and Fan Wang"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "BFW Equilibrium Gender LFP and Wage Code Companion"
output:
  pdf_document:
    toc: true
    toc_depth: 5
    pandoc_args: '_output_kniti_pdf.yaml'
    includes:
      in_header: 'preamble_book.tex'
  html_document:
    pandoc_args: '_output_kniti_html.yaml'
always_allow_html: true
github-repo: fanwangecon/PrjLabEquiBFW
---

```{r global_options, include = FALSE}
source(".Rprofile")
options(bookdown.render.file_scope = FALSE)
```

# Preface {-}

`r text_top_count`

This is a work-in-progress Matlab package consisting of functions that solve the equilibrium gender labor force participation and wage model in [Bhalotra](https://www.iza.org/person/2905/sonia-r-bhalotra), [Fernández](https://sites.google.com/view/manuelfernandezsierra) and [Wang](https://fanwangecon.github.io/) (2022). Tested with [Matlab](https://www.mathworks.com/products/matlab.html) 2021b [@matlab].

All functions are parts of a matlab toolbox that can be installed:

> Download and install the Matlab toolbox: [PrjLabEquiBFW.mltbx](https://github.com/FanWangEcon/PrjLabEquiBFW/blob/main/PrjLabEquiBFW.mltbx)

The Code Companion can also be accessed via the bookdown site and PDF linked below:

> [**bookdown site**](https://fanwangecon.github.io/PrjLabEquiBFW/bookdown/), [**bookdown pdf**](https://fanwangecon.github.io/PrjLabEquiBFW/bookdown/BFW-Equilibrium-Gender-LFP-and-Wage-Code-Companion.pdf), [**MathWorks File Exchange**](https://www.mathworks.com/matlabcentral/fileexchange/80164-PrjLabEquiBFW)

This bookdown file is a collection of mlx based vignettes for functions that are available from [PrjLabEquiBFW](https://github.com/FanWangEcon/PrjLabEquiBFW). Each Vignette file contains various examples for invoking each function.

The package relies on [MEconTools](https://fanwangecon.github.io/MEconTools/), which needs to be installed first. The package does not include allocation functions, only simulation code to generate the value of each stimulus check increments for households.

The site is built using [Bookdown](https://bookdown.org/) [@R-bookdown].

Please contact [FanWangEcon](https://fanwangecon.github.io/) for issues or problems.

`r text_end_count`
