---
always_allow_html: 'true'
core:
- code: '[bfw_mp_param_esti()](https://github.com/FanWangEcon/PrjLabEquiBFW/blob/main/PrjLabEquiBFW/paramsdata/bfw_mp_param_esti.m)

    '
  package: PrjLabEquiBFW
date: '2022-02-17'
date_start: '2022-02-17'
description: 'bfw_mp_param_esti

  '
file: bfwx_mp_param_esti
output:
  html_document:
    includes:
      in_header: ../../../hdga.html
    pandoc_args: ../../../_output_kniti_html.yaml
  pdf_document:
    includes:
      in_header: ../../../preamble.tex
    pandoc_args: ../../../_output_kniti_pdf.yaml
title: bfwx_mp_param_esti
titleshort: bfw_mp_param_esti
urlcolor: blue
---

## bfw_mp_param_esti

This is the example vignette for function:
[**bfw_mp_param_esti**](https://github.com/FanWangEcon/PrjLabEquiBFW/tree/main/PrjLabEquiBFW/params/bfw_mp_param_esti.m)
from the [**PrjLabEquiBFW
Package**](https://fanwangecon.github.io/PrjLabEquiBFW/)**.**

### Map of Estimated Parameters

    bl_log_wage = true;
    bl_verbose = true;
    mp_func_supply = bfw_mp_param_esti(bl_log_wage, bl_verbose);

    pos = 42 ; key = mp_rho_nests
      Map with properties:

            Count: 11
          KeyType: char
        ValueType: any

    pos = 43 ; key = mp_rho_nests_init
      Map with properties:

            Count: 8
          KeyType: char
        ValueType: any

    ----------------------------------------
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    CONTAINER NAME: mp_params ND Array (Matrix etc)
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                         i     idx    ndim    numel    rowN    colN      sum         mean        std      coefvari      min          max   
                         __    ___    ____    _____    ____    ____    ________    ________    _______    ________    ________    _________

        ar_alpha_A001     1     1      2        4       1       4      -0.94699    -0.23675    0.51665     -2.1823     -1.0101     0.068567
        ar_alpha_A002     2     2      2        4       1       4       -1.4489    -0.36221     0.7982     -2.2037     -1.5565      0.11544
        ar_alpha_A003     3     3      2        4       1       4      -0.57104    -0.14276    0.31287     -2.1916      -0.611      0.04301
        ar_alpha_AA01     4     4      2        4       1       4      -0.67951    -0.16988     0.3633     -2.1386    -0.71418      0.03661
        ar_alpha_AA02     5     5      2        4       1       4       -0.6718    -0.16795    0.33676     -2.0051    -0.67309     0.001573
        ar_alpha_B001     6     6      2        4       1       4       -1.2904    -0.32261    0.67446     -2.0907     -1.3337     0.046411
        ar_alpha_B002     7     7      2        4       1       4       -1.1023    -0.27558    0.57386     -2.0823     -1.1359     0.036755
        ar_alpha_B003     8     8      2        4       1       4      -0.85037    -0.21259    0.44078     -2.0734    -0.87352      0.02499
        ar_alpha_B101     9     9      2        4       1       4       -2.7486    -0.68715     1.4441     -2.1015      -2.852      0.10452
        ar_alpha_B102    10    10      2        4       1       4       -1.3642    -0.34105    0.66492     -1.9496     -1.3382    0.0046709
        ar_alpha_B103    11    11      2        4       1       4       -1.1457    -0.28641    0.57331     -2.0017     -1.1464     0.002346
        arpie_f_s        12    12      2        6       1       6        4.6479     0.77464     6.3115      8.1476     -8.3485       11.145
        arpie_f_u        13    13      2        6       1       6        8.0344      1.3391      4.861      3.6302     -2.0749       11.145
        arpie_k_s        14    14      2        6       1       6        1.3887     0.23145     1.8386      7.9441     -3.0311       2.4457
        arpie_k_u        15    15      2        6       1       6        4.7387     0.78979     1.8849      2.3866     -2.2809       3.0169
        arpsi0_f_s       16    16      2        3       1       3        3.3528      1.1176     1.0974      0.9819           0       2.1936
        arpsi0_f_u       17    17      2        3       1       3         20.22        6.74    0.55777    0.082755      6.3081       7.3697
        arpsi0_k_s       18    18      2        3       1       3         1.779     0.59299    0.68939      1.1626           0       1.3494
        arpsi0_k_u       19    19      2        3       1       3        18.003      6.0009    0.84112     0.14016      5.0649       6.6935

    xxx TABLE:ar_alpha_A001 xxxxxxxxxxxxxxxxxx
                  c1            c2           c3         c4   
              __________    __________    ________    _______

        r1    0.00013396    -0.0056187    0.068567    -1.0101

    xxx TABLE:ar_alpha_A002 xxxxxxxxxxxxxxxxxx
                  c1            c2          c3         c4   
              __________    __________    _______    _______

        r1    0.00017171    -0.0079274    0.11544    -1.5565

    xxx TABLE:ar_alpha_A003 xxxxxxxxxxxxxxxxxx
                  c1            c2          c3         c4  
              __________    __________    _______    ______

        r1    6.9362e-05    -0.0031181    0.04301    -0.611

    xxx TABLE:ar_alpha_AA01 xxxxxxxxxxxxxxxxxx
                  c1           c2          c3          c4   
              __________    _________    _______    ________

        r1    3.3671e-05    -0.001978    0.03661    -0.71418

    xxx TABLE:ar_alpha_AA02 xxxxxxxxxxxxxxxxxx
                  c1            c2            c3          c4   
              __________    ___________    ________    ________

        r1    9.8127e-06    -0.00029501    0.001573    -0.67309

    xxx TABLE:ar_alpha_B001 xxxxxxxxxxxxxxxxxx
                  c1            c2           c3         c4   
              __________    __________    ________    _______

        r1    7.1149e-05    -0.0031771    0.046411    -1.3337

    xxx TABLE:ar_alpha_B002 xxxxxxxxxxxxxxxxxx
                  c1            c2           c3         c4   
              __________    __________    ________    _______

        r1    7.7753e-05    -0.0032235    0.036755    -1.1359

    xxx TABLE:ar_alpha_B003 xxxxxxxxxxxxxxxxxx
                  c1            c2          c3          c4   
              __________    __________    _______    ________

        r1    4.3028e-05    -0.0018888    0.02499    -0.87352

    xxx TABLE:ar_alpha_B101 xxxxxxxxxxxxxxxxxx
                  c1             c2          c3         c4  
              ___________    __________    _______    ______

        r1    -1.7675e-05    -0.0011106    0.10452    -2.852

    xxx TABLE:ar_alpha_B102 xxxxxxxxxxxxxxxxxx
                  c1            c2           c3          c4   
              ___________    _________    _________    _______

        r1    -0.00010096    0.0046709    -0.030629    -1.3382

    xxx TABLE:ar_alpha_B103 xxxxxxxxxxxxxxxxxx
                  c1            c2           c3          c4   
              ___________    ________    __________    _______

        r1    -7.5369e-05    0.002346    -0.0015487    -1.1464

    xxx TABLE:arpie_f_s xxxxxxxxxxxxxxxxxx
                c1      c2      c3        c4         c5         c6   
              ______    __    ______    _______    _______    _______

        r1    11.145    0     2.7351    0.26746    -8.3485    -1.1508

    xxx TABLE:arpie_f_u xxxxxxxxxxxxxxxxxx
                c1      c2       c3          c4         c5         c6   
              ______    __    ________    ________    _______    _______

        r1    11.145    0     -0.25662    -0.26519    -2.0749    -0.5135

    xxx TABLE:arpie_k_s xxxxxxxxxxxxxxxxxx
                c1      c2       c3          c4         c5         c6  
              ______    __    _________    _______    _______    ______

        r1    2.4457    0     -0.043896    0.91566    -3.0311    1.1023

    xxx TABLE:arpie_k_u xxxxxxxxxxxxxxxxxx
                c1      c2      c3         c4        c5         c6   
              ______    __    _______    ______    _______    _______

        r1    2.4457    0     -2.2809    3.0169    0.84513    0.71184

    xxx TABLE:arpsi0_f_s xxxxxxxxxxxxxxxxxx
              c1      c2        c3  
              __    ______    ______

        r1    0     1.1592    2.1936

    xxx TABLE:arpsi0_f_u xxxxxxxxxxxxxxxxxx
                c1        c2        c3  
              ______    ______    ______

        r1    7.3697    6.5422    6.3081

    xxx TABLE:arpsi0_k_s xxxxxxxxxxxxxxxxxx
              c1      c2         c3  
              __    _______    ______

        r1    0     0.42958    1.3494

    xxx TABLE:arpsi0_k_u xxxxxxxxxxxxxxxxxx
                c1        c2        c3  
              ______    ______    ______

        r1    6.6935    6.2443    5.0649

    ----------------------------------------
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    CONTAINER NAME: mp_params Scalars
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                                            i     idx     value  
                                            __    ___    ________

        bl_log_wage                          1    20            1
        fl_rho_abstract_vs_manualroutine     2    21     0.031411
        fl_rho_gen_abstract                  3    22      0.65979
        fl_rho_gen_manual                    4    23     0.083519
        fl_rho_gen_routine                   5    24      0.21769
        fl_rho_routine_vs_manual             6    25     -0.15438
        fl_rho_skill_abstract                7    26      0.30231
        fl_rho_skill_manual                  8    27      0.73852
        fl_rho_skill_routine                 9    28      0.30052
        fl_yzagg_y1989                      10    29       1.4905
        fl_yzagg_y1992                      11    30       1.4602
        fl_yzagg_y1994                      12    31       1.6493
        fl_yzagg_y1996                      13    32       1.7686
        fl_yzagg_y1998                      14    33       1.8018
        fl_yzagg_y2000                      15    34       2.0599
        fl_yzagg_y2002                      16    35       2.0597
        fl_yzagg_y2004                      17    36       2.2803
        fl_yzagg_y2005                      18    37       2.3392
        fl_yzagg_y2008                      19    38       2.4908
        fl_yzagg_y2010                      20    39       2.7153
        fl_yzagg_y2012                      21    40        2.822
        fl_yzagg_y2014                      22    41       2.8707
        psi1                                23    44      0.96625
